server:
  port: 8080
  servlet:
    context-path: / 
    

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul
    username: spring
    password: 1q2w3e4r5t!
    

mybatis:
  mapper-locations: mapper/*.xml


